### ISSUE TITLE
Backward gradient error

### ISSUE THREAD

**Issue by inspirit** [lucidrains/ETSformer-pytorch#1]
Hello,

i was trying to run the provided class and see following error:
`Function ScatterBackward0 returned an invalid gradient at index 1 - got [64, 4, 128] but expected shape compatible with [64, 33, 128]`

```
model = ETSFormer(
            time_features = 9,
            model_dim = 128,
            embed_kernel_size = 3,
            layers = 2,
            heads = 4,
            K = 4,
            dropout = 0.2
        )
```

`input = torch.rand(64, 64, 9)`
`x = model(input, num_steps_forecast = 16)`

**Comment by lucidrains** [comment]
@inspirit :wave: using the repository so soon! i'm not very confident about all the code yet, just as warning :laughing: 

i fixed the issue you were facing https://github.com/lucidrains/ETSformer-pytorch/commit/51d66b49094c957fbb434bded061e0dca1dc4792 , let me know if it works for you now

**Comment by inspirit** [comment]
thanks a lot! that fixed the error with backward gradient

**Comment by lucidrains** [comment]
@inspirit cool, if you find some :bug: :lady_beetle: , do send a pull request :D

**Comment by lucidrains** [comment]
@inspirit i think the way i'm doing fourier extrapolation may not be most efficient :(
