### ISSUE TITLE
growth_term calculation error

### ISSUE THREAD

**Issue by inspirit** [lucidrains/ETSformer-pytorch#2]
https://github.com/lucidrains/ETSformer-pytorch/blob/e1d8514b44d113ead523aa6307986833e68eecc5/etsformer_pytorch/etsformer_pytorch.py#L233-L235

It looks like you are not using `growth` and `growth_smoothing_weights`to calculate `growth_term`

**Comment by lucidrains** [comment]
@inspirit :man_facepalming: oh yes, thank you for catching that! https://github.com/lucidrains/ETSformer-pytorch/commit/ace5ac92b2f2c1d8e4c561d09ab36e161bbc1ccf :pray:

**Comment by lucidrains** [comment]
@inspirit do let me know if you get positive results with this architecture, and if you end up benchmarking this against vanilla ETS (which was not in the paper) :pray:

**Comment by inspirit** [comment]
> @inspirit 🤦‍♂️ oh yes, thank you for catching that! [ace5ac9](https://github.com/lucidrains/ETSformer-pytorch/commit/ace5ac92b2f2c1d8e4c561d09ab36e161bbc1ccf) 🙏

it looks like 
`growth = self.to_growth(latent_growth)`
still not used for anything :)

**Comment by lucidrains** [comment]
@inspirit https://github.com/lucidrains/ETSformer-pytorch/commit/2e0d465576c15fc8d84c4673f93fdd71d45b799c oops lol
