### ISSUE TITLE
wrong order of arguments

### ISSUE THREAD

**Issue by inspirit** [lucidrains/ETSformer-pytorch#3]
https://github.com/lucidrains/ETSformer-pytorch/blob/2e0d465576c15fc8d84c4673f93fdd71d45b799c/etsformer_pytorch/etsformer_pytorch.py#L327

you pass latents on wrong order to Level module:
according to forward method first should be growth and then seasonal

**Comment by lucidrains** [comment]
@inspirit https://github.com/lucidrains/ETSformer-pytorch/commit/86ba87c13580d15dc0671bbd83a0f04d52391bf6 thank you!
