### ISSUE TITLE
What are your thoughts on using latents for additional classification task

### ISSUE THREAD

**Issue by inspirit** [lucidrains/ETSformer-pytorch#5]
Hi! I was wondering if you have thought about aggregating seasonal and growth latents for additional tasks (for example classification)? What are the possible ways to bring latents into single feature vector in your opinion?
The easiest one would be just get the mean along layers and time dimensions but that seams to be too naive.
Another idea I had it to use Cross Attention mechanic with single time query key to aggregate latents:
```
all_latents = torch.cat([latent_growths, latent_seasonals], dim=-1)
all_latents = rearrange(all_latents, 'b n l d -> (b l) n d')
# q = nn.Parameter(torch.randn(all_latents_dim))
q = repeat(q, 'd -> b 1 d', b = all_latents.shape[0])
agg_latent = cross_attention(query=q, context=all_latents)
agg_latent = rearrange(all_latents, '(b l) n d -> b (l n) d')
agg_latent = agg_latent.mean(dim=1) # may be we should have done it before cross attention?
```

Would be great to hear your thoughts

**Comment by lucidrains** [comment]
@inspirit yup, (cross) attention pooling would be a good fit :) it has been proven out by perceiver as well as few vision transformer variants

**Comment by lucidrains** [comment]
i think the output of the level E should be attended to as well, let me add that to the list of returnables

**Comment by inspirit** [comment]
hmm E output seems valid point i wonder how would you combine it with growth and seasonal since that have different structure:
growth/seasonal : [b, n, l, d]
E : [b, n, t]
?

**Comment by lucidrains** [comment]
you can simply run a convolution on E into `Ek` and `Ev` and let the queries attend to it as well

**Comment by inspirit** [comment]
so you mean to 2 cross attentions sequentially?
```
q = cross_att1(q,  latent_growths_seasonal)
q = cross_att2(q, E)
```

**Comment by lucidrains** [comment]
more like `attended = cross_attn(queries, concat(to_key_values(latent_growths_seasonal), conv_to_key_values(E)))`

may also give growths, seasonal, and level output their own type embedding first

**Comment by lucidrains** [comment]
i can build it in the next 15 minutes if you are willing to share your findings (positive or negative)

**Comment by inspirit** [comment]
yup would be helpful I am testing it with 2 consecutive losses at the moment one forecast as intended and another is classification for different problem that correlate with forecasting, happy to share the results

**Comment by lucidrains** [comment]
@inspirit ok, building it :laughing: gimme 15-20

**Comment by lucidrains** [comment]
@inspirit  https://github.com/lucidrains/ETSformer-pytorch/commit/0c4d19012abde708418e35a93496e3207832bcd7

lemme know

**Comment by inspirit** [comment]
I would also allow for forecast results to be an output along with Intermediate latents so that the class can be used for multitasking.

**Comment by lucidrains** [comment]
will do later tonight!

**Comment by lucidrains** [comment]
@inspirit done https://github.com/lucidrains/ETSformer-pytorch/blob/main/etsformer_pytorch/etsformer_pytorch.py#L373

**Comment by inspirit** [comment]
super thanx!

**Comment by tmm1** [comment]
@inspirit what was your experience using this for classification?
