### ISSUE TITLE
Pre LayerNorm might be required for k,v?

### ISSUE THREAD

**Issue by inspirit** [lucidrains/ETSformer-pytorch#6]
https://github.com/lucidrains/ETSformer-pytorch/blob/2561053007e919409b3255eb1d0852c68799d24f/etsformer_pytorch/etsformer_pytorch.py#L440

In my early tests I see some instability in training results, I was wondering if it might be good idea to LayerNorm latents before constructing key and values?

**Comment by lucidrains** [comment]
@inspirit never hurts to add layer norms :) https://github.com/lucidrains/ETSformer-pytorch/commit/a762af838a00e8ff3e54faa82e52d568025da694

**Comment by lucidrains** [comment]
@inspirit are you seeing signs of life with this architecture? to be honest, i was a little skeptical at lack of inclusion of plain ETS as a baseline, and that the results they have didn't require much depth (2 layers)

**Comment by lucidrains** [comment]
@inspirit time series is one of attention net's weakest points, so anything you can reveal would be helpful! :pray:

**Comment by lucidrains** [comment]
@inspirit changed it to after the projection (before doesn't make much sense) https://github.com/lucidrains/ETSformer-pytorch/commit/60f10fb198b4b53e905894109ba074acf76082a1

**Comment by inspirit** [comment]
hey, so far cant say anything positive, simple PerceiverIO gives better results for me, still trying different ideas

**Comment by lucidrains** [comment]
@inspirit :pray: thank you for sharing that!
