### ISSUE TITLE
Does ETS-Former allow adding features

### ISSUE THREAD

**Issue by StatMixedML** [lucidrains/ETSformer-pytorch#7]
@lucidrains Thanks for making the code of the model available!

In your paper, you state that the model infers seasonal patterns itself, so that there is no need to add time features like week, month, etc.

Still, to increase the applicability of your approach, does the current implementation allow to add any (time-invariant and time-varying) features, e.g., categorical or numeric?

**Comment by lucidrains** [comment]
@StatMixedML Hey Alexander! This is actually not my paper, I simply built it because I was curious about its claims

If you are seeing positive results, do let me know and perhaps I can entertain the idea of doing some improvising and adding more of the features you mentioned

**Comment by StatMixedML** [comment]
Ok thanks @lucidrains, will do. I close this for now.
